version: "3.4"

networks:
  nginx-network:
    external: true

services:
  some_service_1:
    image: some:latest
    command: runuwsgi --port 80
    hostname: some-01
    environment:
      VIRTUAL_HOST: first.some.test

      UWSGI_UID: 1000
      UWSGI_GID: 1000
      UWSGI_MASTER_AS_ROOT: 1
      UWSGI_THUNDER_LOCK: 1

    networks:
      nginx-network:
        aliases:
          - first.some.test

  some_service_2:
    image: some:latest
    entrypoint: authbind python3 manage.py
    command: rungunicorn gunicorn_conf
    hostname: some-02
    environment:
      VIRTUAL_HOST: second.some.test

      GUNICORN_BIND: 0.0.0.0:80
      GUNICORN_WORKERS: 2
      GUNICORN_TIMEOUT: 10

    networks:
      nginx-network:
        aliases:
          - second.some.test
